import type { AgentCardData } from '@/components/marketplace/AgentCard';

export const PLACEHOLDER_AGENTS: AgentCardData[] = [
  {
    id: '1',
    slug: 'shopify-returns-handler',
    name: 'Shopify Returns Handler',
    description: 'Automatically processes return requests, generates shipping labels, and sends customer updates via email.',
    category: 'ecommerce',
    pricing_model: 'monthly',
    price_cents: 2900,
    avg_rating: 4.8,
    review_count: 124,
    total_rentals: 1850,
    creator_name: 'AutomateHQ',
    tags: ['shopify', 'returns', 'email'],
    stats: { speed: 72, accuracy: 85, reliability: 91, popularity: 78, versatility: 64 },
  },
  {
    id: '2',
    slug: 'smart-email-responder',
    name: 'Smart Email Responder',
    description: 'Reads incoming support emails, classifies intent, drafts contextual responses, and routes complex cases to humans.',
    category: 'customer-support',
    pricing_model: 'monthly',
    price_cents: 1900,
    avg_rating: 4.6,
    review_count: 89,
    total_rentals: 2340,
    creator_name: 'MailBot Labs',
    tags: ['gmail', 'support', 'auto-reply'],
    stats: { speed: 88, accuracy: 76, reliability: 82, popularity: 85, versatility: 48 },
  },
  {
    id: '3',
    slug: 'lead-qualifier-pro',
    name: 'Lead Qualifier Pro',
    description: 'Scores inbound leads using CRM data, enriches profiles, and automatically assigns to the right sales rep.',
    category: 'sales',
    pricing_model: 'monthly',
    price_cents: 4900,
    avg_rating: 4.9,
    review_count: 67,
    total_rentals: 890,
    creator_name: 'SalesSpark AI',
    tags: ['hubspot', 'leads', 'scoring'],
    stats: { speed: 65, accuracy: 94, reliability: 88, popularity: 62, versatility: 48 },
  },
  {
    id: '4',
    slug: 'social-content-creator',
    name: 'Social Content Creator',
    description: 'Generates branded social media posts, schedules content across platforms, and suggests optimal posting times.',
    category: 'marketing',
    pricing_model: 'monthly',
    price_cents: 3900,
    avg_rating: 4.5,
    review_count: 156,
    total_rentals: 3200,
    creator_name: 'ContentForge',
    tags: ['social', 'scheduling', 'content'],
    stats: { speed: 80, accuracy: 68, reliability: 74, popularity: 90, versatility: 80 },
  },
  {
    id: '5',
    slug: 'invoice-processor',
    name: 'Invoice Processor',
    description: 'Extracts data from invoices, matches to purchase orders, flags discrepancies, and syncs with your accounting system.',
    category: 'finance',
    pricing_model: 'per_use',
    price_cents: 15,
    avg_rating: 4.7,
    review_count: 201,
    total_rentals: 4100,
    creator_name: 'FinBot',
    tags: ['invoices', 'accounting', 'ocr'],
    stats: { speed: 55, accuracy: 96, reliability: 92, popularity: 88, versatility: 32 },
  },
  {
    id: '6',
    slug: 'slack-standup-bot',
    name: 'Slack Standup Bot',
    description: 'Collects async standups from team members, summarizes blockers, and posts a daily digest to your channel.',
    category: 'productivity',
    pricing_model: 'free',
    price_cents: 0,
    avg_rating: 4.4,
    review_count: 312,
    total_rentals: 8700,
    creator_name: 'TeamFlow',
    tags: ['slack', 'standup', 'team'],
    stats: { speed: 92, accuracy: 70, reliability: 85, popularity: 95, versatility: 32 },
  },
  {
    id: '7',
    slug: 'resume-screener',
    name: 'Resume Screener',
    description: 'Analyzes resumes against job requirements, ranks candidates, and generates shortlist with reasoning.',
    category: 'hr',
    pricing_model: 'per_use',
    price_cents: 50,
    avg_rating: 4.3,
    review_count: 45,
    total_rentals: 560,
    creator_name: 'HireAI',
    tags: ['recruiting', 'resume', 'screening'],
    stats: { speed: 60, accuracy: 82, reliability: 78, popularity: 45, versatility: 32 },
  },
  {
    id: '8',
    slug: 'data-pipeline-monitor',
    name: 'Data Pipeline Monitor',
    description: 'Monitors your data pipelines for anomalies, alerts on failures, and provides root cause analysis.',
    category: 'data',
    pricing_model: 'monthly',
    price_cents: 5900,
    avg_rating: 4.8,
    review_count: 34,
    total_rentals: 420,
    creator_name: 'DataOps AI',
    tags: ['monitoring', 'alerts', 'analytics'],
    stats: { speed: 45, accuracy: 90, reliability: 95, popularity: 38, versatility: 48 },
  },
  {
    id: '9',
    slug: 'code-review-assistant',
    name: 'Code Review Assistant',
    description: 'Reviews pull requests for bugs, security issues, and style violations. Provides inline suggestions.',
    category: 'development',
    pricing_model: 'monthly',
    price_cents: 2900,
    avg_rating: 4.6,
    review_count: 178,
    total_rentals: 2900,
    creator_name: 'DevToolsAI',
    tags: ['github', 'code-review', 'security'],
    stats: { speed: 50, accuracy: 88, reliability: 84, popularity: 82, versatility: 48 },
  },
  {
    id: '10',
    slug: 'blog-writer-pro',
    name: 'Blog Writer Pro',
    description: 'Researches topics, generates SEO-optimized blog posts, and publishes directly to your CMS.',
    category: 'content',
    pricing_model: 'per_use',
    price_cents: 200,
    avg_rating: 4.2,
    review_count: 92,
    total_rentals: 1450,
    creator_name: 'WriteBot',
    tags: ['blog', 'seo', 'writing'],
    stats: { speed: 35, accuracy: 72, reliability: 70, popularity: 68, versatility: 48 },
  },
  {
    id: '11',
    slug: 'order-fulfillment-agent',
    name: 'Order Fulfillment Agent',
    description: 'Tracks orders across warehouses, updates shipping status, and handles customer delivery inquiries.',
    category: 'operations',
    pricing_model: 'monthly',
    price_cents: 3900,
    avg_rating: 4.7,
    review_count: 56,
    total_rentals: 780,
    creator_name: 'OpsFlow',
    tags: ['fulfillment', 'shipping', 'tracking'],
    stats: { speed: 68, accuracy: 86, reliability: 90, popularity: 55, versatility: 64 },
  },
  {
    id: '12',
    slug: 'webhook-transformer',
    name: 'Webhook Transformer',
    description: 'Catches incoming webhooks, transforms payloads to your schema, and routes data to the right service.',
    category: 'utility',
    pricing_model: 'free',
    price_cents: 0,
    avg_rating: 4.5,
    review_count: 203,
    total_rentals: 5600,
    creator_name: 'UtilityAI',
    tags: ['webhook', 'api', 'transform'],
    stats: { speed: 95, accuracy: 80, reliability: 88, popularity: 92, versatility: 80 },
  },
];
